---
sidebar: sidebar 
permalink: Architectual.migrate_data_into_vds.html 
summary: 移轉資料時的考量摘要 
keywords:  
---
= 資料移轉考量
:allow-uri-read: 




== 總覽

移轉至任何類型的雲端解決方案時、移轉資料幾乎是通用的需求。雖然管理員負責將資料移轉至虛擬桌面、但NetApp的經驗已成為可用的經驗、而且已證實對於無數客戶移轉來說是非常寶貴的經驗。虛擬桌面環境只是託管的Windows環境、因此很可能會採用任何所需的方法。

.一般移轉的資料：
* 使用者設定檔（桌面、文件、我的最愛等）
* 檔案伺服器共用
* 資料共用（應用程式資料、資料庫、備份快取）


.在虛擬桌面環境中、有兩個主要位置可儲存及組織資料：
* 使用者（通常為H：\）磁碟機：這是每個使用者可見的對應磁碟機。
+
** 這會對應回<drive>:\home\CustomerCode\user.name路徑
** 每個使用者都有自己的H:\磁碟機、而且看不到其他使用者


* 共享磁碟機（通常為I:\）：這是所有使用者都能看到的共享對應磁碟機
+
** 這會對應回<drive>:\data\CustomerCode\路徑
** 所有使用者都可以存取此磁碟機。在VDS的「資料夾」區段中、會管理其對內含資料夾/檔案的存取層級。






== 一般移轉程序

. 將資料複寫到雲端環境
. 將資料移至適當的H：\和I：\磁碟機路徑
. 在虛擬桌面環境中指派適當的權限




== FTPS傳輸與考量



=== 使用FTPS移轉

. 如果在SWA部署程序期間啟用了FTPS伺服器角色、請登入VDS、瀏覽至「報告」並執行貴組織的主用戶端報告、以收集FTPS認證資料
. 上傳資料
. 將資料移至H：\和I：\磁碟機的適當路徑
. 透過資料夾模組在虛擬桌面環境中指派適當的權限



NOTE: 透過FTPS傳輸資料時、任何中斷都會使資料無法如預期傳輸。由於虛擬桌面服務管理的伺服器每晚都會重新開機、因此標準的夜間傳輸策略可能會中斷。為了避免這種情況、管理員可以啟用移轉模式、以防止VM重新開機1週。

輕鬆啟用移轉模式：瀏覽至組織、然後向下捲動至「Virtual Desktop Settings」（虛擬桌面設定）區段、勾選「Migration Mode」（移轉模式）方塊、然後按一下「Update」（更新）。


NOTE: NetApp建議系統管理員啟用法規遵循設定、協助組織透過強化部署閘道等來達成PCI、HIPAA及NIST控制。這也會使預設的FTP伺服器角色（若已啟用）不接受透過連接埠21進行的預設未加密傳輸。FileZilla不允許SFTP、這表示應使用FTPS透過連接埠990建立連線。

若要啟用該設定、請連線至CWMGR1並瀏覽至CwVmAutomationService程式、然後啟用PCI v3法規遵循。



== 同步工具與考量

企業檔案同步與共享（通常稱為EFSS或同步工具）在移轉資料時非常實用、因為此工具會在每一端擷取變更、直到轉換為止。Office 365隨附的OneDrive等工具可協助您同步檔案伺服器資料。這也適用於VDI使用者部署、因為使用者與VM之間有1：1關係、只要使用者在共享資料部署一次時（通常為I：\）、不會嘗試將共享內容同步到VDI伺服器。 推動整個組織使用。移轉SQL和類似資料（開放式檔案）

.通用同步和/或移轉解決方案不會傳輸開啟的檔案、包括下列檔案類型：
* 信箱（.ost）檔案
* 快速書籍檔案
* Microsoft Access檔案
* SQL資料庫


這表示如果整個檔案（例如出現1封新電子郵件）或資料庫（在應用程式的系統中輸入1筆新記錄）的單一元素、則整個檔案會有所不同、而且是標準的同步工具（例如Dropbox）。 會認為這是全新的檔案、需要重新移動。如有需要、可向第三方供應商購買專用工具。

處理這些移轉的另一種常見方法是提供第三方VAR的存取權限、而第三方VAR通常會簡化匯入/匯出資料庫的作業。



== 運送磁碟機

許多資料中心供應商不再隨附硬碟、也不需要您遵守特定的政策與程序。

Microsoft Azure讓組織能夠使用Azure Data Box、管理員可與Microsoft代表協調、充分發揮Azure Data Box的優勢。
