---
sidebar: sidebar 
permalink: Reference.Release_Notes.cws_v5.0_release_notes.html 
summary: NetApp VDS發行說明5.0版 
keywords:  
---
= CWS–5.0版發行說明
:allow-uri-read: 



NOTE: 再也不會有適用於CWS 5.0版的重複發行版本、所有版本都會被視為即時修補程式。



== 總覽

CloudJumper已於2016年第4季正式推出Cloud Workspace Suite 5.0、以供一般實作之用。此版本同時包含CWS API和管理控制介面的更新。此版本是重大變更、與4.x版實體「向下相容」。

在所有合作夥伴軟體定義資料中心（SDDC）升級至5.0平台之前、將持續支援4.x版、CloudJumper將與每個合作夥伴協調完成升級、不會中斷現有的服務。無需支付升級費用或執行成本即可移轉。CWS 5持續支援所有舊版的功能、並延伸新功能、強化系統管理員與終端使用者的使用體驗、並進一步改善雲端Workspace Suite先前版本所推出獲獎肯定的自動化與協調功能。

有了CWS 5.0、CloudJumper已將所有平台API重新寫入REST API格式、並完全淘汰舊版的SOAP API。這項更新的架構可讓CloudJumper更輕鬆、更快速地進一步增強功能、為外部開發人員創造更友善的環境、讓他們能夠擴充雲端工作區的服務與產品。



== 重點摘要

* 完整的UI/UX重新寫入
* Azure AD整合
* Azure SDDC自助服務部署
* 應用程式服務
* 資源排程
* 即時伺服器擴充–跨平台
* 自動化伺服器複製：跨平台
* 根據每個用戶端自訂磁碟機共用




== 主要功能



=== Azure Active Directory（AD）整合

* 將SDDC建置為私有雲端Active Directory、或使用Microsoft Azure即服務
* 將CWS與Office365結合使用
* 支援Azure型SSO與MFA




=== Azure SDDC自助服務部署

* 與Azure完全整合
* 快速部署新的SDDC
* 在Azure內部署私有企業雲端、以因應任何工作負載、包括受管理的Cloud Workspace：WAAS, App Services, Private Web App和SharePoint




=== 應用程式服務

* 部署應用程式封閉環境、將應用程式發佈為隔離的服務建置區塊
* 應用程式從「公有」應用程式伺服器提供給許多自訂實體
* 安裝在單一應用程式專屬伺服器集區中的應用程式
* 應用程式可與使用者設定檔和資料層需求分離
* 建置超可擴充的應用程式服務
* 多種應用程式服務可整合至使用者集合
* CWS授權追蹤與使用量報告




=== 即時伺服器擴充–跨平台

* 智慧型自動擴充伺服器資源/作用中伺服器
* 在使用者負載變更時、以動態增加/減少的方式來緊密管理伺服器資源
* 隨著工作負載變化、自動上下擴充伺服器資源




=== 自動化伺服器複製：跨平台

* 自動增加伺服器、直到根據定義的使用者數量增加計算可用度為止
* 將其他伺服器新增至可用的資源集區
* 結合CWS Live Server Scaling功能、打造全自動化解決方案




=== 資源排程

* 根據每位客戶排程服務時間
* 公有雲的成本控制
* 不使用時關閉系統、並依照預先定義的排程重新啟動

