---
sidebar: sidebar 
permalink: Troubleshooting.application_issues.html 
summary: 疑難排解應用程式問題的逐步指南 
keywords:  
---
= 疑難排解應用程式問題
:allow-uri-read: 




== 總覽

疑難排解應用程式錯誤是一種常見的管理實務做法，不涉及VDS本身，但VDS及其提供的系統管理員控制層級可大幅輔助。雖然NetApp VDS並未針對客戶疑難排解這些問題、但我們的經驗可讓我們在識別下列基本資訊之後、建議系統管理員深入探索並與終端使用者及/或第三方進行疑難排解。

* 發生問題的使用者名稱
* 使用者使用的應用程式名稱
* 使用者工作階段所在的伺服器
* 重現問題的步驟




== 檢閱您的工具



=== 監控

識別使用者所使用的伺服器之後、請檢查您的監控解決方案、以驗證資源（CPU和RAM）使用量是否在正常層級內。您也可以驗證應用程式特定需求（特殊服務、如果未執行、將會導致問題）是否正常運作。在這種情況下、可能會觸發進階設定、例如對上述服務的上/下監控。



=== 防毒

身為同時存取伺服器和Azure Active Directory的系統管理員、您有權檢閱已探索到的內容、以及已設定的原則。萬一出現無法預期的情況、可能會影響您的應用程式。



=== 其他工具

有些應用程式需要額外的元件、例如無限期登入的服務帳戶、或是連至實體設備的VPN（例如現場網路應用裝置、製造設備或診斷公用程式）。在這些情況下、應用程式特定的錯誤可能是由應用程式安裝方式以外的其他項目所造成、或是應用程式設定的方式所造成。



=== 擴大第三方存取範圍

應用程式及/或其資料庫通常由軟體廠商（ISV）本身或軟體組態、管理及整合的第三方專家來安裝、設定及支援。在這些情況下、您會想要將暫時管理存取權限延伸至下列步驟： link:Management.System_Administration.provide_3rd_party_access.html["提供第三方的暫時存取權限"]

最佳做法是在升級或更新完成或問題解決後、關閉這些第三方帳戶。

在許多情況下、這種疑難排解等級需要與ISV簽訂軟體維護合約。如果未安裝、ISV可能會在安裝之前協助您。


NOTE: 疑難排解問題也可能與終端使用者所使用的硬體（桌上型電腦、筆記型電腦、精簡型用戶端等）有關。例如、升級使用者的筆記型電腦可能會將機器鎖定在精簡型用戶端組態檔案的眼中、這表示終端使用者無法存取可讓他們登入虛擬桌面的工具。在這種情況下、可能需要簽訂硬體維護合約、製造商才能協助您。
