= 總覽
:allow-uri-read: 




== 總覽

_include/TODO/Management.command_center.operations.add_existing_server_to_company.adoc Management.command_center.operations.backup_restore_to_drive.adoc Management.command_center.operations.change_data_home_pro_folders.adoc Management.command_center.operations.create_azure_file_share.adoc Management.command_center.operations.create_data_center_site.adoc Management.command_center.operations.create_server_from_clone.adoc Management.command_center.operations.create_template_phase_3.adoc Management.command_center.operations.delete_datacenter_site.adoc Management.command_center.operations.delete_template.adoc Management.command_center.operations.edit_workload_schedule.adoc Management.command_center.operations.file_migration.adoc Management.command_center.operations.install_notepad++_Chrome.adoc _include/TODO/Management.command_center.operations.allow_new_AVD_connections.adoc _include/TODO/TODO/Management.command_center.operations.backup_list.adoc _include/TODO/Management.command_center.operations.backups_run_all_scheduled.adoc _include/TODO/Management.command_center.operations.copy_template_to_gallery.adoc _include/TODO/TODO/Management.command_center.operations.create_cache_company.adoc Management.command_center.operations.backup_server_now.adoc _include/TODO/Management.command_center.operations.create_server_from_backup.adoc Management.command_center.operations.change_password.adoc _include/TODO/TODO/TODO/Management.command_center.operations.create_no_server_company.adoc _Management.command_center.operations.create_azure_netapp_files_share.adoc Management.command_center.operations.create_server_from_template.adoc Management.command_center.operations.create_template_phase_1.adoc Management.command_center.operations.created_company.adoc Management.command_center.operations.delete_drives_from_server.adoc Management.command_center.operations.edit_provisioning_collection.adoc Management.command_center.operations.exclude_server_from_monitoring.adoc Management.command_center.operations.generate_email_reports.adoc Management.command_center.operations.install_thinprint_license_server.adoc Management.command_center.operations.delete_backup.adoc _include/TODO/Management.command_center.operations.delete_server.adoc Management.command_center.operations.edit_resource_pool.adoc Management.command_center.operations.expand_drive.adoc _include/TODO/TODO/TODO/Management.command_center.operations.generate_reports.adoc Management.command_center.operations.list_drives_for_server.adoc _include/TODO/TODO/TODO/TODO/TODO/_包括Management.command_center.operations.list_long_running_operations.adoc Management.command_center.operations.load_active_users.adoc Management.command_center.operations.load_cache_companies.adoc Management.command_center.operations.load_hypervisor_config_options.adoc Management.command_center.operations.load_hypervisor_type.adoc Management.command_center.operations.load_machine_series.adoc Management.command_center.operations.load_machine_sizes.adoc Management.command_center.operations.load_max_concurrent_users.adoc Management.command_center.operations.load_resource_pool_data.adoc Management.command_center.operations.load_server_resource_report_data.adoc Management.command_center.operations.load_servers_for_company.adoc Management.command_center.operations.load_storage_types.adoc Management.command_center.operations.load_templates.adoc Management.command_center.operations.load_virtual_machines.adoc _include/TODO/Management.command_center.operations.make_server_active.adoc _include/TODO/Management.command_center.operations.make_server_data_server.adoc _include/TODO/Management.command_center.operations.migrate_company.adoc _include/TODO/Management.command_center.operations.move_servers_to_company.adoc Management.command_center.operations.reload_monitored_applications.adoc Management.command_center.operations.resource_allocation_enable.adoc Management.command_center.operations.run_program.adoc Management.command_center.operations.set_external_dns.adoc Management.command_center.operations.should_pool_be_running.adoc Management.command_center.operations.start_server.adoc Management.command_center.operations.stop_sddc.adoc Management.command_center.operations.update_active_user_count.adoc Management.command_center.operations.wildcard_cert_install.adoc _include/TODO/Management.command_center.operations.reload_configuration.adoc Management.command_center.operations.reboot_server.adoc _include/TODO/TODO/Management.command_center.operations.rename_server.adoc Management.command_center.operations.run_daily_maintenance.adoc _include/TODO/TODO/Management.command_center.operations.run_workload_schedule.adoc _Management.command_center.operations.remove_vds_software.adoc _include/TODO/TODO/Management.command_center.operations.run_resource_allocation.adoc Management.command_center.operations.run_daily_actions.adoc _Management.command_center.operations.start_server_for_wake_on_demand.adoc包括Management.command_center.operations.set_gateway_address.adoc Management.command_center.operations.set_time_zone.adoc Management.command_center.operations.start_company.adoc Management.command_center.operations.stop_company.adoc Management.command_center.operations.stop_server.adoc Management.command_center.operations.update_cw_vm_automation_service.adoc _include/TODO/TODO/TODO/TODO/Management.command_center.operations.stop_cwagent.adoc Management.command_center.operations.test_hypervisor_connection.adoc Management.command_center.operations.wildcard_cert_create_new.adoc
